# Playbook to setup workstation and create osp network, router, SG and ssh keypair

- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation
       ansible_python_interpreter: /usr/bin/python3.7


- hosts: workstation
  become: yes
  roles:
    - setup-workstation
  vars:
    ansbible_python_interpreter: /usr/bin/python

- import_playbook: site-install-isolated-node.yml 

