- hosts: workstation
  become: true
  gather_facts: false 
  tasks:
    -name: test 
       debug:
         msg: wtf
#  roles:
#    - osp-servers
  vars:
    ansible_python_interpreter: /usr/bin/python3
