---
# defaults file for osp.servers
#cloud: ospcloud
#int_network: int_network
#ext_network: ext_network
#openstack_pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBTCYfp/LvJHpyMqZBeXoX/jHz/LB4yAeRBMYLf3V/kopcIetQQHYIkgW96LB9CmQABX9heoopsDK8tj5IZgz//dPqfYapm+S4mz8jIOFvIwmUle6iM2KdBvMGqIBKiURVoTwQZZMoWzZEqmaHFrRuNrZCDUJ8B3LmNBqp3UQtnYUuG2Vtg/q94Wqlv7nGiBJ/bT0HhPjrsFGXJs29F354rK3Xp9KeKO9RB2PYNgIJ22KFNOZ3IV67I5bd2uJQXHEuQYqAenHh/cIt1GicOVGHKr9RQOngz4093/tuVfiwhIyKZVWu4Xm3G8x6v9nyg4ifi5XSBNvXBCuXSdivv+yd"
#opentlc_pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBI0NDSAtj82BAwNgc26QHbiO2OYJ0sR6teUuqEe/GI21u+PrEHB8UCj8gEj2583Ph2ImFzBlIVCbGEszC43cMqQH/H7lx9kwjDA7dg8IhcMURADRmnqiGXQaYwI7ixYObDz9rtrDOg5dv1Ja25wG2kUUkNU5vJiN5Uuuc485na3nwwKVQES+K5GoHZPz4rIsP24zpay321h2bOodcfZ83/hkzne66U9FnQlySANAJCEbGq7FyFNgfGEpWCHtsJDvE4TFYQVB2uEd+gF6YlhnQRor8x9nAZBZrR6rrPJz4dSmAea83yA6wv/sWaYPGv0hCyzDIZpm+Xp5DFApGSymp opentlc-mgr@admin.na.shared.opentlc.com"
