- name: yum clean
  shell: yum clean all
  
- name: Enable tower repo for python3
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}" 
    baseurl: "{{ item.baseurl }}"
    gpgcheck: no
    enabled: yes
  loop: "{{ tower_repo }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install python3 and python3-pip
  yum:
    name:
      - python3.x86_64
      - python3-pip.noarch

- name: Install openstacksdk library
  pip:
    name: openstacksdk
    state: latest
    extra_args: -U
- name: Create clouds.yaml file
  blockinfile:
    create: yes
    path: /etc/openstack/clouds.yaml
    block: |2
      clouds:
        ospcloud:
          auth:
            auth_url: http://192.168.0.20:5000/
            password: r3dh4t1!
            project_name: admin
            username: admin
          identity_api_version: '3'
          region_name: RegionOne
- name: Set openstack.pub authorized key from file
  authorized_key:
    user: cloud-user
    state: present
    key: "{{ lookup('file', '/root/.ssh/openstack.pub') }}"
